[build]
  # 构建命令
  command = "npm run build"
  # 发布目录
  publish = "."

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# 重定向规则 - SPA路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置 - 安全和性能优化
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HSTS - HTTP严格传输安全
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # CSP - 内容安全策略
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com https://apis.google.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://*.firebaseio.com https://*.googleapis.com; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # Permissions Policy - 权限策略
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"

# CSS和JS文件缓存
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML文件不缓存
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 字体文件缓存
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 图片文件缓存
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"